"""estado inicial do banco

Revision ID: 158becbc9c75
Revises: 
Create Date: 2026-05-30 11:54:19.535530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158becbc9c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('Usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('aluno', 'personal', 'admin', name='tipousuario'), nullable=True),
    sa.Column('personal_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Exercicios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('base', 'customizado', name='tipoexercicio'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Convites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('personal_id', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuarios', type_='foreignkey')
    op.drop_column('Usuarios', 'personal_id')
    op.drop_column('Usuarios', 'senha')
    op.drop_table('Convites')
    op.drop_table('Exercicios')
    # ### end Alembic commands ###
