"""Adicionar campo de senha

Revision ID: 5dae9aa95fc8
Revises: 4d2eb2c9783b
Create Date: 2026-05-28 12:17:39.280890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dae9aa95fc8'
down_revision: Union[str, Sequence[str], None] = '4d2eb2c9783b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('senha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'senha')
    # ### end Alembic commands ###
