"""adicionar tabelas treinos e treino exercicios

Revision ID: 67b5329aa0fc
Revises: 158becbc9c75
Create Date: 2026-06-02 10:49:51.799037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b5329aa0fc'
down_revision: Union[str, Sequence[str], None] = '158becbc9c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Treinos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criado_por', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('personal', 'proprio', name='tipotreino'), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TreinoExercicios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('treino_id', sa.String(), nullable=True),
    sa.Column('exercicio_id', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['Exercicios.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['Treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.alter_column('Usuarios', 'senha',
#existing_type=sa.VARCHAR(),
#nullable=False)
    #op.create_foreign_key(None, 'Usuarios', 'Usuarios', ['personal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'Usuarios', type_='foreignkey')
    #op.alter_column('Usuarios', 'senha',
#            existing_type=sa.VARCHAR(),
#            nullable=True)
    op.drop_table('TreinoExercicios')
    op.drop_table('Treinos')
    # ### end Alembic commands ###
